export const teachers = [
  {
    id: "0021",
    name: "Floyd Miles",
    avatar: "https://i.pravatar.cc/150?img=1",
    address: "TA-107 Newyork",
    subject: "Mathematics",
    class: "01",
    phone: "+123 9988568",
    
    gender: "Male"
  },
  {
    id: "0011",
    name: "Jane Cooper",
    avatar: "https://i.pravatar.cc/150?img=2",
    address: "Australia, Sydney",
    subject: "English",
    class: "02",
    phone: "+123 7988566",
    
    gender: "Female"
  },
  {
    id: "0031",
    name: "Jenny Wilson",
    avatar: "https://i.pravatar.cc/150?img=3",
    address: "TA-107 Newyork",
    subject: "Physics",
    class: "03",
    phone: "+123 7988567",
    
    gender: "Male"
  },
  {
    id: "0022",
    name: "Annette Black",
    avatar: "https://i.pravatar.cc/150?img=4",
    address: "Australia, Sydney",
    subject: "Literature",
    class: "04",
    phone: "+123 5988565",
    
    gender: "Female"
  },
  {
    id: "0013",
    name: "Arlene McCoy",
    avatar: "https://i.pravatar.cc/150?img=5",
    address: "TA-107 Newyork",
    subject: "Mathematics",
    class: "04",
    phone: "+123 4948564",
    
    gender: "Female"
  },
  {
    id: "0014",
    name: "Robert Fox",
    avatar: "https://i.pravatar.cc/150?img=6",
    address: "TA-107 Newyork",
    subject: "English",
    class: "03",
    phone: "+123 3983563",
    
    gender: "Female"
  },
  {
    id: "0018",
    name: "Arlene McCoy",
    avatar: "https://i.pravatar.cc/150?img=7",
    address: "Australia, Sydney",
    subject: "Physics",
    class: "01",
    phone: "+123 4988555",
    
    gender: "Female"
  },
  {
    id: "0017",
    name: "Albert Flores",
    avatar: "https://i.pravatar.cc/150?img=8",
    address: "TA-107 Newyork",
    subject: "Mathematics",
    class: "01",
    phone: "+123 6988566",
    
    gender: "Female"
  },
  {
    id: "0019",
    name: "Devon Lane",
    avatar: "https://i.pravatar.cc/150?img=9",
    address: "Australia, Sydney",
    subject: "Literature",
    class: "02",
    phone: "+123 9988568",
    
    gender: "Male"
  },
];

export const students = [
  {
    id: "SCH-2026-001",
    name: "Chukwudi Adebayo",
    image: "https://i.pravatar.cc/150?u=nig001",
    class: "SSS 3",
    category: "Secondary",
    gender: "Male",
    // house: "Yellow (Justice)",
    term_average: 84.5,
    class_position: "3rd",
    parent_name: "Mr. & Mrs. Adebayo",
    parent_phone: "08030000001",
    residential_address: "Lekki Phase 1, Lagos",
    // blood_group: "O+",
    // status: "Boarding",
  },
  {
    id: "SCH-2026-002",
    name: "Amina Abubakar",
    image: "https://i.pravatar.cc/150?u=nig002",
    class: "SSS 2",
    category: "Secondary",
    gender: "Female",
    // house: "Blue (Loyalty)",
    term_average: 91.2,
    class_position: "1st",
    parent_name: "Alhaji Abubakar",
    parent_phone: "08140000002",
    residential_address: "Maitama, Abuja",
    // blood_group: "AA",
    // status: "Day Student",
  },
  {
    id: "SCH-2026-003",
    name: "Oluwaseun Balogun",
    image: "https://i.pravatar.cc/150?u=nig003",
    class: "Primary 5",
    category: "Primary",
    gender: "Male",
    // house: "Red (Valour)",
    term_average: 72.8,
    class_position: "12th",
    parent_name: "Dr. Balogun",
    parent_phone: "07060000003",
    residential_address: "Bodija, Ibadan",
    // blood_group: "B+",
    // status: "Day Student",
  },
  {
    id: "SCH-2026-004",
    name: "Nneka Okoro",
    image: "https://i.pravatar.cc/150?u=nig004",
    class: "JSS 2",
    category: "Secondary",
    gender: "Female",
    // house: "Green (Peace)",
    term_average: 65.0,
    class_position: "20th",
    parent_name: "Mrs. Okoro",
    parent_phone: "09050000004",
    residential_address: "Independence Layout, Enugu",
    // blood_group: "A+",
    // status: "Boarding",
  },
  {
    id: "SCH-2026-005",
    name: "Tunde Bakare",
    image: "https://i.pravatar.cc/150?u=nig005",
    class: "SSS 1",
    category: "Secondary",
    gender: "Male",
    // house: "Yellow (Justice)",
    term_average: 78.4,
    class_position: "5th",
    parent_name: "Engr. Bakare",
    parent_phone: "08020000005",
    residential_address: "GRA, Ikeja",
    // blood_group: "O-",
    // status: "Boarding",
  },
  {
    id: "SCH-2026-006",
    name: "Fatima Umar",
    image: "https://i.pravatar.cc/150?u=nig006",
    class: "Primary 2",
    category: "Primary",
    gender: "Female",
    // house: "Blue (Loyalty)",
    term_average: 88.9,
    class_position: "2nd",
    parent_name: "Mallam Umar",
    parent_phone: "08130000006",
    residential_address: "Kano Road, Kaduna",
    // blood_group: "AA",
    // status: "Day Student",
  },
  {
    id: "SCH-2026-007",
    name: "Ibrahim Danjuma",
    image: "https://i.pravatar.cc/150?u=nig007",
    class: "JSS 3",
    category: "Secondary",
    gender: "Male",
    // house: "Red (Valour)",
    term_average: 54.2,
    class_position: "35th",
    parent_name: "Mr. Danjuma",
    parent_phone: "07080000007",
    residential_address: "Rayfield, Jos",
    // blood_group: "AS",
    // status: "Boarding",
  },
  {
    id: "SCH-2026-008",
    name: "Efe Omoware",
    image: "https://i.pravatar.cc/150?u=nig008",
    class: "SSS 3",
    category: "Secondary",
    gender: "Female",
    // house: "Green (Peace)",
    term_average: 82.1,
    class_position: "4th",
    parent_name: "Chief Omoware",
    parent_phone: "08070000008",
    residential_address: "Warri, Delta",
    // blood_group: "O+",
    // status: "Boarding",
  },
  {
    id: "SCH-2026-009",
    name: "Zainab Yusuf",
    image: "https://i.pravatar.cc/150?u=nig009",
    class: "Primary 6",
    category: "Primary",
    gender: "Female",
    // house: "Yellow (Justice)",
    term_average: 76.3,
    class_position: "8th",
    parent_name: "Mrs. Yusuf",
    parent_phone: "08100000009",
    residential_address: "Gwarinpa, Abuja",
    // blood_group: "AA",
    // status: "Day Student",
  },
  {
    id: "SCH-2026-010",
    name: "Kelechi Nnamdi",
    image: "https://i.pravatar.cc/150?u=nig010",
    class: "JSS 1",
    category: "Secondary",
    gender: "Male",
    // house: "Blue (Loyalty)",
    term_average: 69.8,
    class_position: "15th",
    parent_name: "Mr. Nnamdi",
    parent_phone: "08031111110",
    residential_address: "Aba, Abia",
    // blood_group: "AS",
    // status: "Boarding",
  },
  {
    id: "SCH-2026-011",
    name: "Funmi Ajayi",
    image: "https://i.pravatar.cc/150?u=nig011",
    class: "Primary 4",
    category: "Primary",
    gender: "Female",
    // house: "Red (Valour)",
    term_average: 94.0,
    class_position: "1st",
    parent_name: "Mr. Ajayi",
    parent_phone: "08022222211",
    residential_address: "Akure, Ondo",
    // blood_group: "O+",
    // status: "Day Student",
  },
  {
    id: "SCH-2026-012",
    name: "Umar Farouq",
    image: "https://i.pravatar.cc/150?u=nig012",
    class: "SSS 2",
    category: "Secondary",
    gender: "Male",
    // house: "Green (Peace)",
    term_average: 61.5,
    class_position: "22nd",
    parent_name: "Alhaji Farouq",
    parent_phone: "08133333312",
    residential_address: "Sokoto Road, Katsina",
    // blood_group: "AA",
    // status: "Day Student",
  },
  {
    id: "SCH-2026-013",
    name: "Blessing Etim",
    image: "https://i.pravatar.cc/150?u=nig013",
    class: "Primary 3",
    category: "Primary",
    gender: "Female",
    // house: "Blue (Loyalty)",
    term_average: 79.2,
    class_position: "6th",
    parent_name: "Mr. Etim",
    parent_phone: "09011111113",
    residential_address: "Uyo, Akwa Ibom",
    // blood_group: "A-",
    // status: "Day Student",
  },
  {
    id: "SCH-2026-014",
    name: "Damilola Oke",
    image: "https://i.pravatar.cc/150?u=nig014",
    class: "SSS 1",
    category: "Secondary",
    gender: "Male",
    // house: "Yellow (Justice)",
    term_average: 87.0,
    class_position: "2nd",
    parent_name: "Chief Oke",
    parent_phone: "08055555514",
    residential_address: "Abeokuta, Ogun",
    // blood_group: "O+",
    // status: "Boarding",
  },
  {
    id: "SCH-2026-015",
    name: "Chiamaka Eze",
    image: "https://i.pravatar.cc/150?u=nig015",
    class: "JSS 3",
    category: "Secondary",
    gender: "Female",
    // house: "Red (Valour)",
    term_average: 70.5,
    class_position: "11th",
    parent_name: "Mrs. Eze",
    parent_phone: "07044444415",
    residential_address: "Asaba, Delta",
    // blood_group: "AA",
    // status: "Boarding",
  },
];
